### ISSUE TITLE
URL prefix cannot be removed

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#2099]
**Affected version(s)**

Contao 4.10.0-RC2

- Set URL prefix and klick save
- Delete the URL prefix and klick save

`Error message: The URL prefix "" is already used by another root page with the same domain name!`

![url-prefix](https://user-images.githubusercontent.com/1942550/89437233-9c1cbb80-d747-11ea-9d1f-6863d4140d38.png)

I only use one root page in my setup.

**Comment by ausi** [comment]
I think this was already fixed in #2042

**Comment by leofeyer** [comment]
@netzarbeiter Does the issue still occur in Contao 4.10.0-RC3?

**Comment by netzarbeiter** [comment]
I have disabled the legacy routing and now it works.

Thank you very much.
