### ISSUE TITLE
Content include element broken with fragments

### ISSUE THREAD

**Issue by dmolineus** [contao/contao#2823]
**Affected version(s)**

Contao 4.9 or Contao 4.10?

**Description**

If I include a content element which is a fragment controller with the content alias element Contao selects the wrong element class for the rendering. The issue appears because the element id is overridden here: https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/core-bundle/src/Resources/contao/elements/ContentAlias.php#L42

**Comment by leofeyer** [comment]
How does your fragment controller look like?

**Comment by dmolineus** [comment]
You can have a look at this example. The expected value would be `test`, but it will return `alias` as the alias model is used. Be aware that not only the wrong content model is used but also any changes made by `ContentAlias` get lost.

```php

<?php

declare(strict_types=1);

use Contao\ContentModel;
use Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController;
use Contao\CoreBundle\ServiceAnnotation\ContentElement;
use Contao\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @ContentElement("test", category="text")
 */
class TestElementController extends AbstractContentElementController
{
    protected function getResponse(Template $template, ContentModel $model, Request $request): ?Response
    {
        return new Response($model->type);
    }
}

$controller = new TestElementController();
$response   = $controller->__invoke($request, $model, $section, $classes);

assert($response->getContent() === 'text');
assert($response->getContent() === 'alias');
```

**Comment by leofeyer** [comment]
@aschempp Is this also fixed by #2851?

**Comment by aschempp** [comment]
Well by #2930 I would say

**Comment by zonky2** [comment]
it is not fixed if this is a CE-MM list/filter or FE module MM list/filter
