### ISSUE TITLE
CSS ID/class not applied to FrontendModules as CE

### ISSUE THREAD

**Issue by bennyborn** [contao/contao#3532]
When creating a custom Front End Module using `AbstractFrontendModuleController` (as described in the [docs](https://docs.contao.org/dev/framework/front-end-modules/)) it seems that Contao does not apply the CSS ID and Class given to the Content Element referencing the Module.

![image](https://user-images.githubusercontent.com/226890/135610591-f49b92e2-67fc-433f-9969-bd74f27c56d0.png)
![image](https://user-images.githubusercontent.com/226890/135610307-4186b729-5904-48b7-bf36-967e644c8aad.png)

This is definitely not the case when using an "oldschool" Module.

**Comment by aschempp** [comment]
Are you on the latest Contao version? Because this should be fixed recently.

**Comment by bennyborn** [comment]
The project in question is version `4.9.20`.

**Update:** Still not working in `4.9.21`

**Comment by ameotoko** [comment]
I can confirm, `cssID` is not applied from content element, if module is created as `AbstractFrontendModuleController`. Just tested on `4.12.1`, but I think it has always been an issue

**Comment by ameotoko** [comment]
Seems like a typo; #4056 fixes it for me.

**Comment by m-vo** [comment]
see #4056
