### ISSUE TITLE
Notification of new comments - Invalid URL after changing alias

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#373]
**Affected version(s)**
4.4.x & 4.6.x

**Description**  
If someone has activated the notification for new comments and I later changes the alias of the page or news, then the wrong URLs are sent.

**How to reproduce**  
Tested with the news.

1. Write a new comment
2. Activate notification
3. Change the alias of the news article
4. Add new comment
5. Notification is sent from Contao
6. This mail contains the old URL (from the DB) and therefore causes a 404 error when you click on the link.

The URL is stored in the table "tl_comments_notify".
Would it be possible to generate the URL at runtime so changing the alias does not lead to a 404 error?

Also the url to cancel the notification is wrong and don't work any more.

**Comment by leofeyer** [comment]
We need to discuss this. Comments can be everywhere (pages, articles, news, events, etc.), therefore generating the URL at runtime is not trivial.

BTW, should you not set up a 301 redirect if you change a page alias?

**Comment by contaoacademy** [comment]
> BTW, should you not set up a 301 redirect if you change a page alias?

Yeah, from an SEO point of view, you're absolutely right. And it won't happen that often.
Nevertheless there are now incorrect URLS in the database ;-)

**Comment by leofeyer** [comment]
As discussed in Mumble on May 9th, we actually do not need to store the URL in the database, because we can always use the current URL (on which the comments form has been submitted).

However, we cannot fix the case that someone has an old e-mail with a wrong link. You have to set up a 301 redirect page to cover this.

**Comment by leofeyer** [comment]
Unfortunately, this does not work as intended. If you subscribe to a comment, you will also be notified of author replies, which are added in the back end.

**Comment by leofeyer** [comment]
As discussed again on June 6th, we still have to store the URLs for the author replies in the back end, but we can use the "live" URL if someone comments in the front end.

**Comment by leofeyer** [comment]
Fixed in abdb71e64967695ec9bdfcda06aac38163cab9a0.

**Comment by frontendschlampe** [comment]
If I understand correctly you have fixed the issue using the current URL in notification mail.

I have the same issue now with Contao 4.13.30 and the user still get a notification mail with the old URL.
