### ISSUE TITLE
Invalid type for path "contao.prepend_locale"

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#4161]
### Affected version(s)

4.13.0

### Description

Our backwards compatibility to the old `%prepend_locale%` parameter does not seem to work anymore in newer Contao versions. i.e. if you have

```yaml
parameters:
    prepend_locale: true
```

in your `config/parameters.yaml`, the following error will occur:

```
Symfony\Component\Config\Definition\Exception\InvalidTypeException:
Invalid type for path "contao.prepend_locale". Expected "bool", but got "string".
Hint: Whether or not to add the page language to the URL.

  at vendor\symfony\config\Definition\BooleanNode.php:29
  at Symfony\Component\Config\Definition\BooleanNode->validateType('%prepend_locale%')
     (vendor\symfony\config\Definition\BaseNode.php:564)
  at Symfony\Component\Config\Definition\BaseNode->doValidateType('%prepend_locale%')
     (vendor\symfony\config\Definition\BaseNode.php:407)
  at Symfony\Component\Config\Definition\BaseNode->normalize('%prepend_locale%')
     (vendor\symfony\config\Definition\ArrayNode.php:287)
  at Symfony\Component\Config\Definition\ArrayNode->normalizeValue(array('prepend_locale' => '%prepend_locale%'))
     (vendor\symfony\config\Definition\BaseNode.php:410)
  at Symfony\Component\Config\Definition\BaseNode->normalize(array('prepend_locale' => '%prepend_locale%'))
     (vendor\symfony\config\Definition\Processor.php:32)
  at Symfony\Component\Config\Definition\Processor->process(object(ArrayNode), array(array('preview_script' => '/preview.php'), array('legacy_routing' => false, 'localconfig' => array('licenseAccepted' => true, 'installPassword' => '…', 'adminEmail' => '…'), 'mailer' => …, array('prepend_locale' => '%prepend_locale%')))
     (vendor\symfony\config\Definition\Processor.php:46)
  at Symfony\Component\Config\Definition\Processor->processConfiguration …
````

**Comment by aschempp** [comment]
This looks like a Symfony/YAML bug if they read `true` as a string? Or maybe something changed in Symfony 5.4?

**Comment by fritzmg** [comment]
`'%prepend_locale%'` is a string though. I haven't looked into it yet, but it seems the parameter is not resolved anymore at that point.

**Comment by aschempp** [comment]
We're only adding the parameter if it exists in the container (https://github.com/contao/contao/blob/5.x/manager-bundle/src/ContaoManager/Plugin.php#L262), so yeah maybe somehow Symfony does not _load_ it anymore?

**Comment by rorych** [comment]
Is there any update here or is it currently not possible to use "prepend_locale" without changing to the new routing_mode?

**Comment by fritzmg** [comment]
@rorych just do the following:

```yaml
# config/config.yaml
contao:
    prepend_locale: true
```

Using `parameters.prepend_locale` is deprecated.

**Comment by leofeyer** [comment]
I cannot confirm this. I have added `prepend_locale: true` to my config file and run `clear:cache` afterwards. No exception.

**Comment by fritzmg** [comment]
> I cannot confirm this. I have added `prepend_locale: true` to my config file

Which one? `config/config.yaml` or `config/parameters.yaml`? This issue concerns the latter.

**Comment by fritzmg** [comment]
I can still confirm the issue. Reproduction:

1. Create a file called `config/parameters.yaml`
2. Insert the following content:
    ```yaml
    parameters:
        prepend_locale: true
    ```
3. Execute the following command: `rm -rf var && vendor/bin/contao-console cache:warmup`

The following error will occur:

```
$ rm -rf var && vendor/bin/contao-console cache:warmup

In BooleanNode.php line 29:

  Invalid type for path "contao.prepend_locale". Expected "bool", but got "string".  
  Hint: Whether or not to add the page language to the URL.
```

**Comment by leofeyer** [comment]
Ok, I can reproduce it now. Is there a way to fix this without changing `->booleanNode('prepend_locale')`?

**Comment by fritzmg** [comment]
Changing the node would not be correct - for some reason the parameter (`'%prepend_locale%'`) is not evaluated (or present?) when the config is evaluated by Symfony. So far I have not figured out why.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4437

**Comment by christianromeni** [comment]
btw.. same thing happens to ```pretty_error_screens```
At least for me... But only if I use '%env(bool:PRETTY_ERROR)%' instead of ```true```
I use env.local to set this parameter: ```PRETTY_ERROR=false```

config.yaml
```
contao:
  pretty_error_screens: '%env(bool:PRETTY_ERROR)%'
  prepend_locale: true
  backend:
    attributes:
      app-name: 'xyz'
      app-version: '%env(VERSION)%'
    badge_title: '%env(BADGE_TITLE)%'
```

.env.local
```
APP_ENV="dev"
BADGE_TITLE='DEV'
PRETTY_ERROR=false
```

**Comment by aschempp** [comment]
pretty sure thats fixed by #4437 as well, did you check that?

**Comment by christianromeni** [comment]
If that is in 4.13.2 then I don't think it's fixed..
If it is not released yet, I have not checked it... 🙈

**Comment by ausi** [comment]
#4437 was not released yet. You have to test `4.13.x-dev` to see if the fix works for you.

**Comment by christianromeni** [comment]
Ok, so I finally got the time to continue with my project, and it actually is still not working in Contao 4.13.4

```
Invalid type for path "contao.pretty_error_screens". Expected "bool", but got "string".
Hint: Show customizable, pretty error screens instead of the default PHP error messages.
```

Still the same config as mentioned in [here](https://github.com/contao/contao/issues/4161#issuecomment-1086407959)

**Comment by fritzmg** [comment]
@christianromeni that's a different error message, referencing a completely different config. Please seek help in the Contao community.

**Comment by christianromeni** [comment]
@fritzmg Yes, because I disabled the setting for the composer update, so I could update to the latest version.. And check if it works..
This is the error I get in the frontend.. But during the installation, it was the error mentioned above.

```
In BooleanNode.php line 29:
                                                                               
  Invalid type for path "contao.pretty_error_screens". Expected "bool", but g  
  ot "string".                                                                 
  Hint: Show customizable, pretty error screens instead of the default PHP er  
  ror messages. 
```
