### ISSUE TITLE
Breadcrumb on 404 page leads to system log error entry

### ISSUE THREAD

**Issue by Mynyx** [contao/contao#4194]
### Affected version(s)

4.13.0

### Description

If a 404 error page contains a  breadcrumb navigation, each page view leads to an error entry in the system log: ``Unable to generate URL for page ID X: Page ID X is not routable``

**Comment by Total-Reality** [comment]
This is true. 

You can test it out in the demo:
https://demo.contao.org/contao?do=log&ref=KmDrgQ3o

https://demo.contao.org/preview.php/en/contao/preview?page=19

It also happens on 401 pages:
https://demo.contao.org/preview.php/contao/preview?page=16

Btw. the preview bar is missing on the 401 page. Is this another bug?

**Comment by aschempp** [comment]
This should have been fixed by https://github.com/contao/contao/pull/3947, maybe that change didn't make it upstream (yet)?

**Comment by tarun-uwe** [comment]
The Code for the Log message is still / again available in Contao 4.13.1 and 5.x 

https://github.com/contao/contao/blob/c3344b2d3088ddc5c57a04afe67b2379bd820234/core-bundle/src/Resources/contao/modules/ModuleBreadcrumb.php#L259-L261

The pull request mentioned by @aschempp seems only to be merged for 4.12 but afterward is lost?

Do we need a new one for Contao 4.13 and 5.x or will it be added later?

**Comment by olli1770** [comment]
The error is still present in 4.13.2, so breadcrumb is is unuseable at the moment.
Is there still somebody working on it?

**Comment by olli1770** [comment]
And still present in 4.13.4
The log is flooded with : Unable to generate URL for page ID 101: Page ID 101 is not routable

**Comment by Toflar** [comment]
Looks correct to me? It works but it logs because you have to fix it.

**Comment by fritzmg** [comment]
We removed the logging though.

@olli1770 please post a screenshot of the detail view of the log message.

**Comment by tarun-uwe** [comment]
> We removed the logging though.
> 
> @olli1770 please post a screenshot of the detail view of the log message.

Hi @fritzmg the logging was removed for/in Contao 4.12 but did make it back into Contao 4.13 and Contao 5 Branch.
