### ISSUE TITLE
Cannot save news entries with start time 00:00 when using UTC greater than zero

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#436]
**Affected version(s)**
4.7.4

**Description**  
If your configured time zone is greater than UTC and you try to save a news entry whose time is between 00:00 and whatever UTC time offset you have, you'll get the following error:
```
An exception occurred while executing 'UPDATE tl_news SET `time`=-3600 WHERE id='7'':

SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'time' at row 1
```

**How to reproduce**  

1. Set your timezone in the system settings to Europe/Vienna for example.
2. Create a new news entry on any date, but with the time 00:00 for example.
3. Save the news entry.

The aforementioned error should occur.

According to a forum user the error does not occur with every SQL server version. I can reproduce it with MariaDB 10.3.14.

**Comment by joehi** [comment]
Contao 4.7.4

With php 7.3.4 and MariaDB 10.3.14 these errors occur.
With php 7.2.17 and mariaDB 10.1.37 there are no errors.

See also my forum [posting](https://community.contao.org/de/showthread.php?74662-Nachrichten-lassen-sich-nicht-mit-Zeitangabe-00-00-Uhr-anlegen&p=501468&viewfull=1#post501468).

**Comment by leofeyer** [comment]
It seems we need to change

https://github.com/contao/contao/blob/85d8290a25bd796ff5c5c864e0c43d1b46537f8c/news-bundle/src/Resources/contao/dca/tl_news.php#L234

to `int(10) NOT NULL default '0'`. However, I wonder why the issue does not occur in Contao 4.4? Did you test it?

**Comment by joehi** [comment]
I just set up Contao 4.4.38 on the server with php 7.3.4 and MariaDB 10.3.14 and tested it. Same problem as with Contao 4.7.4. So the same issue also occurs with Contao 4.4.

**Comment by leofeyer** [comment]
Fixed in f6a37e734e0c9d7245175d5db984b4b4a5ffa4ad.

**Comment by Helrunar** [comment]
Still not working ... I have updated from 4.4.34 to 4.4.44 and got the same error

**Comment by leofeyer** [comment]
Did you update the database in the Contao install tool?

**Comment by Helrunar** [comment]
Yes i did and all work fine except the update of tl_news
