### ISSUE TITLE
JSON data type with MariaDB

### ISSUE THREAD

**Issue by de-es** [contao/contao#7890]
### Affected version(s)

5.5.0-RC1

### Description

Bei der Migration bleibt eine immer offen, da es den Datentyp `JSON` in [MariaDB](https://mariadb.com/kb/en/json-data-type/) anscheinend nicht gibt und hier `LONGTEXT` genommen wird. In der DB ist der `trustPath` auch effektiv `LONGTEXT`.

```
Pending database migrations (e410dee27d3826e2f06750a2d2a20cf6adfa945fb9ca180a9a2fe86a19f94215)
----------------------------------------------------------------------------------------------

 * ALTER TABLE webauthn_credentials CHANGE trustPath trustPath JSON NOT NULL
```

MariaDB - meine lokale Version 11.6.2 - habe ich entsprechend konfiguriert (Bsp):

```
# Since doctrine/dbal 3.7
# DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=11.6.2-MariaDB"
```

**Comment by aschempp** [comment]
inwiefern ist das ein Problem, bzw. was sollen wir hier ändern?

**Comment by fritzmg** [comment]
For reference: we are extending from an entity of `web-auth/webauthn-lib` which uses a `TrustPath` type which is then mapped to the [`TrustPathDataType`](https://github.com/web-auth/webauthn-symfony-bundle/blob/41381f18894b9a655a946f4a6a982579c5e209b4/src/Doctrine/Type/TrustPathDataType.php) - which in turn uses the `JSON` type. From version 10.4.3, MariaDb aliases JSON to LONGTEXT and adds a constraint. All of this is supported by Doctrine - however, the introspection seems to fail and thus it is always identified as a pending change.

**Comment by ausi** [comment]
This probably needs to be fixed in the doctrine Comparator itself then.

**Comment by EDV-Dozent** [comment]
Gibt es schon eine Timline bis wann das Problem behoben sein wird?
Danke :-)

**Comment by fritzmg** [comment]
@EDV-Dozent you can just ignore it. It does not affect the application.

**Comment by ausi** [comment]
First part of the fix: https://github.com/web-auth/webauthn-framework/pull/698

**Comment by ausi** [comment]
This should be fixed now with version 5.1.3 of `web-auth/webauthn-symfony-bundle`.
Can you please verify if this fixed it for you too?

**Comment by fritzmg** [comment]
We still have a [conflict](https://github.com/contao/conflicts/blob/7591089bcfe9f888a6302db373666fb0be9163bd/composer.json#L35) due to https://github.com/web-auth/webauthn-framework/issues/680 unfortunately.

**Comment by de-es** [comment]
Ja, mit 5.1.3 läuft die Migration ohne o.g. Problem einwandfrei durch. Den Konflikt habe ich zum Testen "entfernt".

**Comment by ausi** [comment]
> We still have a [conflict](https://github.com/contao/conflicts/blob/7591089bcfe9f888a6302db373666fb0be9163bd/composer.json#L35) due to [web-auth/webauthn-framework#680](https://github.com/web-auth/webauthn-framework/issues/680) unfortunately.

Wasn’t this already fixed in https://github.com/web-auth/webauthn-framework/commit/2a013fa0aad14ae689aa8981086249737443d38e ?

**Comment by leofeyer** [comment]
Yes, and apparently the PR has been reassigned to the `5.1` milestone so the changes are present in version 5.1.3 🎉 

→ https://github.com/contao/conflicts/pull/75
