### ISSUE TITLE
Backend display error

### ISSUE THREAD

**Issue by netzarbeiter** [contao/contao#79]
**Affected version(s)**
4.4 and 4.6

**Description**  
In https://github.com/contao/core/issues/8864 we introduced `min-height: 80px;` instead of `height: 80px;` for the class `w50`.

Sometimes there is `min-height: 56px;` added by the class `cbx` which cause a display error in the backend.
![before](https://user-images.githubusercontent.com/1942550/45832716-028ac300-bd03-11e8-8cd5-1a027fe252f8.png)

Deactivating it did the trick.
![after](https://user-images.githubusercontent.com/1942550/45832725-06b6e080-bd03-11e8-8cb6-24cb8d680899.png)

**How to reproduce**  
Go to https://demo.contao.org/contao?do=page&act=edit&id=1

**Comment by leofeyer** [comment]
Works for me in the online demo:

<img width="1032" alt="" src="https://user-images.githubusercontent.com/1192057/45832865-5b5a5b80-bd03-11e8-96b0-8004a042fc1d.png">

Which browser and OS are you using?

**Comment by netzarbeiter** [comment]
macOS and Firefox 62

**Comment by leofeyer** [comment]
It still works for me. Both the text widget and the checkbox widget are 80px high:

<img width="1024" alt="" src="https://user-images.githubusercontent.com/1192057/45864519-8338d600-bd7a-11e8-8e5e-f0b9cb1bbddf.png">

<img width="1024" alt="" src="https://user-images.githubusercontent.com/1192057/45864528-89c74d80-bd7a-11e8-93b0-a3e40a4f68a2.png">

Do you have any browser add-ons installed that alter the rendering?

**Comment by netzarbeiter** [comment]
I have disabled all add-ons, same behavior.

All installations with Contao 4.4.24 are okay, after updating to 4.4.26 there is the mentioned display error.

@alex1971 checked the demo as well, same display error.

**Comment by ausi** [comment]
I can reproduce the issue if I zoom one level in <kbd>⌘ +</kbd> or out <kbd>⌘ -</kbd> in Firefox.

**Comment by leofeyer** [comment]
@netzarbeiter Is this caused by zooming in or a scaled screen resolution?

**Comment by netzarbeiter** [comment]
In my case it is neither caused by zooming nor by a scaled screen resolution.

If I zoom in <kbd>⌘ +</kbd>, out <kbd>⌘ -</kbd> or back <kbd>⌘ 0</kbd> it stays the same.

**Comment by leofeyer** [comment]
Firefox seems to render the text field 30.3 pixel high:

<img width="670" alt="" src="https://user-images.githubusercontent.com/1192057/47298656-a1635180-d618-11e8-821e-1d556b9dc78f.png">

@netzarbeiter Can you please try if adding the following fixes the issue?

```css
.tl_text, .tl_text_2, .tl_text_3, .tl_text_4, .tl_textarea, .tl_text_unit, .tl_text_trbl, .tl_text_interval {
    …
    height: 30px;
}
```

**Comment by netzarbeiter** [comment]
Adding the height fixes the issue.

**Comment by leofeyer** [comment]
@ausi has debugged the issue a bit further. Apparently Firefox does not use the web font for the `input` field (although any input is rendered in Lato):

<img width="363" alt="" src="https://user-images.githubusercontent.com/1192057/47302109-f30fda00-d620-11e8-97b3-32bbeef190b3.png">

We should probably fix this by defining `line-height: 17px` instead of `height: 30px`.

**Comment by leofeyer** [comment]
And while we are on it, we should also check the select menus, which are 81.3px high in Firefox. 😢 

<img width="631" alt="" src="https://user-images.githubusercontent.com/1192057/47302828-bfce4a80-d622-11e8-898b-e7f03cf28360.png">

All of this renders perfectly fine in Chrome and Safari, so thank you for nothing Firefox.

**Comment by leofeyer** [comment]
Fixed in dcf8250acb9ccc30f0519f5544f43e743d29f73a.

**Comment by fritzmg** [comment]
This is still a problem in `4.7.0-RC4`:

![screenshot_2019-02-13 nachrichten blog artikel beitrag id 8 bearbeiten - contao open source cms](https://user-images.githubusercontent.com/4970961/52726907-695f9000-2fb4-11e9-9031-d3c6dad9e987.png)

Chaging the `min-height` to `81px` would fix the issue.

* Windows 10 x64
* Firefox 65.0.1

**Comment by leofeyer** [comment]
Did you make sure that the new format definitions are applied?

**Comment by leofeyer** [comment]
We found out the issue was caused by the changes from #501. Eventually fixed in 98a82d43689e9b5874ef72070060c2ff309df739.

**Comment by fritzmg** [comment]
Unfortunately this still happens:

![Screenshot_2019-10-21 Benachrichtigungen › Benachrichtigung ID 12 editieren](https://user-images.githubusercontent.com/4970961/67214609-f1394c00-f417-11e9-979e-831e9e6453f7.png)

All these widgets have `w50` - however, the very first widget happens to have a height of `80.1` pixels under the following circumstances:

* FireFox 69.0.3
* Windows 10
* dppx 1.25

// edit: more specifically: all widgets with `'chosen' => true` will have a height of `80.1` pixels under these circumstances.

**Comment by leofeyer** [comment]
Maybe we have to limit the height of the chosen dropdown?

**Comment by fritzmg** [comment]
Hm, in this scenario, the `chzn-container` has a height of `29.6px`. Overriding the height to `29px` would fix the problem in Firefox in this state. Not sure if that is the correct solution though.

**Comment by leofeyer** [comment]
How is a height of 29.6px even possible? Can Firefox render 0.6 pixels?

**Comment by fritzmg** [comment]
There can be a lot of situations with subpixels. As I said, this happens with a output device dppx of 1.25.

**Comment by leofeyer** [comment]
I think the actual problem is that the other input fields are only 29px high in Firefox. Chrome and Safari render the fields with a height of 30px, which is correct and matches the height of the Chosen element.

Another example of why Firefox has become the new IE6. 🤷‍♂

**Comment by ausi** [comment]
Safari and Chrome show the same issue for some DPPXs in my test.

<img alt="chrome" src="https://user-images.githubusercontent.com/367169/68620886-bc785c00-04ce-11ea-942c-6c82601856b5.png">

<img alt="safari" src="https://user-images.githubusercontent.com/367169/68620899-c306d380-04ce-11ea-93c0-558ce6e8dd63.png">
