### ISSUE TITLE
Deleting records does not work properly

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#8140]
### Affected version(s)

5.5.x-dev

### Description

If you right click a data record in any data container and select "Delete", a JavaScript confirm dialog will appear where you can confirm or cancel. Confirming the deletion will however make the dialog appear again. If you confirm again it will appear again and so forth.

If you cancel after that you will get the error message

> Cannot load record "tl_….id=…".

as the record was already deleted after the first confirmation.

**Comment by zoglo** [comment]
Is it related to #8109 ?

**Comment by fritzmg** [comment]
No, that has been fixed, i.e. the `rt` parameter is there.

**Comment by fritzmg** [comment]
Clarification: this only happens if you use _Enter_ to confirm the dialog.

**Comment by aschempp** [comment]
this is most likely related to the accessible-menu, because focus is still on the operation and _enter_ could trigger it again. Also see https://github.com/NickDJM/accessible-menu/issues/377 which might be related, but probably is a different side effect of accessibility handling.

**Comment by leofeyer** [comment]
I was not able to reproduce this in Safari.

**Comment by fritzmg** [comment]
I can only reproduce it in Firefox.

**Comment by leofeyer** [comment]
This will most likely be fixed by https://github.com/NickDJM/accessible-menu/pull/386.

**Comment by fritzmg** [comment]
Unfortunately https://github.com/NickDJM/accessible-menu/pull/386 did not fix the issue.

**Comment by aschempp** [comment]
see https://github.com/NickDJM/accessible-menu/pull/392

**Comment by leofeyer** [comment]
@aschempp @fritzmg https://github.com/NickDJM/accessible-menu/pull/395 was merged and released in version 4.2.2, however, I can still reproduce the issue in Firefox after upgrading and rebuilding the assets. Can you, too?

**Comment by fritzmg** [comment]
I can confirm that the issue still occurs with `4.2.2`.
