### ISSUE TITLE
Memory leaks with imagemagick and contao:resize-images

### ISSUE THREAD

**Issue by Toflar** [contao/contao#849]
**Affected version(s)**

4.8.*

**Description**  

When I run `contao:resize-images -c 5 -t 0.1` I regularly run into a memory leak. The regular server pressure is about 2.5GB of memory and if I run the command, I hit the 14GB easily :/ 

**How to reproduce**  

That's going to be a tough one :) Let's see in a bilateral talk if we can do anything about it.

**Comment by ausi** [comment]
I had similar issues for running the command the first time for a project with more than 10.000 images. The memory usage grew endlessly until the process was killed by the hosting provider. I was able to fix my issues by adding the following lines to https://github.com/contao/contao/blob/0d1bb6636c72140a35649ac411339b796fd7c273/core-bundle/src/Command/ResizeImagesCommand.php#L97

```php
Imagick::setResourceLimit(Imagick::RESOURCETYPE_THREAD, 1);
Imagick::setResourceLimit(Imagick::RESOURCETYPE_MEMORY, 1024 * 1024 * 1024);
```

This should make imagemagick use only one core and up to 1 GB of memory.
@Toflar can you test how this behaves in your setup?

**Comment by Toflar** [comment]
First tests show that limiting it only to 1 thread does not help. Up next: Trying to limit only the memory.

**Comment by Toflar** [comment]
Limiting the memory indeed works but I don't know how we should fix this properly. So marking this up for discussion.

**Comment by ausi** [comment]
As discussed on Mumble we want to add a cli argument to limit the memory and default this setting to 1GB.

We should also check if we can use the `throttle` setting of IMagick instead of the custom `sleep()` solution.

**Comment by ausi** [comment]
Another debugging session of @Toflar showed that setting the resource limits doesn’t fix the memory leak but outsources the problem to the disk which might be event worse in some cases I think.

To finally fix the issue we want to use a sub process (similar to how the concurrent feature works now) for every single resize. This should free all resources of imagemagick and the Imagick extension.

**Comment by ausi** [comment]
Closed in favor of #877
